### PR TITLE
Config for lumieres-lausanne test site

### PR DESCRIPTION
**Pull request by gfoo**
Config to redirect to test project site `junipero.unil.ch:10080/resources/IRI`

### CODE REVIEW

**Comment by gfoo** [comment]
Can I disable the test because probably you don't have access to our test server `http://junipero.unil.ch:10080` ?

**Comment by gfoo** [comment]
don't really understand, the ark provided by knora seems not to be correct ?
`https://ark.dasch.swiss/ark:/72163/1/0113/AIae47_ST=q6uanBmib0Wwq`

I launched the ark server on my machine and tried to access to the ark provided:
```shell
$ curl https://0.0.0.0:3336/ark:/72163/1/0113/AIae47_ST=q6uanBmib0Wwq
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```
Docker compose logs:
```
ark_1  | [2019-04-08 15:32:40 +0000] [1] [ERROR] Exception occurred while handling uri: unknown
ark_1  | Traceback (most recent call last):
ark_1  |   File "/usr/local/lib/python3.7/site-packages/sanic/server.py", line 251, in data_received
ark_1  |     self.parser.feed_data(data)
ark_1  |   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
ark_1  | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
```

**Comment by benjamingeer** [comment]
The ARK server doesn't implement HTTPS. If you want to connect to it over HTTPS, you have to put an HTTPS proxy in front of it.

Try the same URL with `http` instead of `https`.

**Comment by gfoo** [comment]
oups ! with http:
```shell
curl http://0.0.0.0:3336/ark:/72163/1/0113/AIae47_ST=q6uanBmib0Wwq

    <h1>Internal Server Error</h1>
    <p>
        The server encountered an internal error and cannot complete
        your request.
    </p>
```

```
ark_1  | [2019-04-08 15:58:20 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:3336/ark:/72163/1/0113/AIae47_ST=q6uanBmib0Wwq'
ark_1  | Traceback (most recent call last):
ark_1  |   File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 750, in handle_request
ark_1  |     response = await response
ark_1  |   File "./ark.py", line 111, in catch_all
ark_1  |     redirect_url = ArkUrlInfo(settings=app.config.settings, ark_url=path, path_only=True).to_redirect_url()
ark_1  |   File "/app/ark_url.py", line 146, in to_redirect_url
ark_1  |     return self.to_php_redirect_url(project_config)
ark_1  |   File "/app/ark_url.py", line 186, in to_php_redirect_url
ark_1  |     resource_int_id = (int(self.resource_id, 16) // self.settings.resource_int_id_factor) - 1
ark_1  | ValueError: invalid literal for int() with base 16: 'AIae47_ST-q6uanBmib0Ww'
ark_1  | [2019-04-08 15:58:20 +0000] - (sanic.access)[INFO][172.30.0.1:40846]: GET http://0.0.0.0:3336/ark:/72163/1/0113/AIae47_ST=q6uanBmib0Wwq  500 144
```

**Comment by benjamingeer** [comment]
Did you accidentally put `UsePhp: true` in your project configuration in the ARK resolver's registry file? That setting is not for Knora projects.

**Comment by gfoo** [comment]
No it is not accidental :) I thought this option allowed to use the template `PhpResourceRedirectUrl: http://$host/resources/$resource_int_id` because I need to redirect arks to `junipero.unil.ch:10080/resources/IRI`.

So I just set the `host` and the default resolver is `http://$host/resources/IRI` ?

**Comment by gfoo** [comment]
oh ! ok I got it.
What I need is somthg similar to that `KnoraResourceRedirectUrl: http://$host/v2/resources/$resource_iri`, but like that `ServerResourceRedirectUrl: http://$host/resources/$resource_iri` but it doesn't exist yet? right ? I will have look tomorow.

**Comment by benjamingeer** [comment]
> No it is not accidental :) I thought this option allowed to use the template PhpResourceRedirectUrl: http://$host/resources/$resource_int_id because I need to redirect arks to junipero.unil.ch:10080/resources/IRI.

The ARK URLs for PHP-based projects are in a completely different format, and the PHP server expects integer resource IDs, not IRIs. So that option won't do what you want at all.

> What I need is somthg similar to that `KnoraResourceRedirectUrl: http://$host/v2/resources/$resource_iri`, but like that `ServerResourceRedirectUrl: http://$host/resources/$resource_iri`

Just make your own project-specific URL template for `KnoraResourceRedirectUrl`, overriding the default template:

```
[0113]
Host: junipero.unil.ch:10080
KnoraResourceRedirectUrl: http://$host/resources/$resource_iri
```

**Comment by gfoo** [comment]
> Why not. The entry "belongs" to the institution. If we would have a GUI where the institutions could update their entries themselves, then it would be their responsibility to add useful entries.

I will update time to time the data, so I will update the test each time

**Pull request merged**
